---
- name: Provision running user with comfortable configs
  hosts: localhost
  tasks:
          - name: copy tmux.conf
            copy: src=tmux.conf dest=~/.tmux.conf 
          - name: set -o vi > bashrc
            lineinfile: path=~/.bashrc line='set -o vi'
          - name: install vim
            block:
                - copy: src=vimrc dest=~/.vimrc
                - file: path=~/.vim/bundle state=directory
                - git: repo=https://github.com/VundleVim/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim
                - command: vim +PluginInstall +qa
